

import '../../../../../data/model/api_response.dart';

abstract class ProfileServiceInterface {
  Future<dynamic> viewUserProfileData();
  Future<dynamic> viewQuestionsList();
  Future<dynamic> viewMotivationList();
  Future<dynamic> viewPersonalityTypeQuestionList();
  Future<dynamic> viewPersonalityTypeCompletedQuestionList();
  Future<dynamic> viewMotivationCompletedAnswerList();
  Future<dynamic> viewCompletedQuestionsList();
  Future<dynamic> getCOTMapperSummary();
  Future<dynamic> viewCOTindividualSummary();
  Future<dynamic> viewSOTmotivationUserList(Map<String, dynamic> loginBody);
  Future<dynamic> viewTribeMeterQuestionList();
  String getUserToken();
  Future<dynamic> updateProfile(Map<String, dynamic> body);
  Future<dynamic> viewPersonalityTypeReport(Map<String, dynamic> body);
  Future<dynamic> viewCOTFunctionalLensDetail(Map<String, dynamic> body);
  Future<dynamic> sendTeamRoleData(Map<String, dynamic> body);
  Future<dynamic> sendPersonalityTypeData(Map<String, dynamic> body);
  Future<dynamic> sendPersonalityCompletedData(Map<String, dynamic> body);
  Future<dynamic> sendMotivationData(Map<String, dynamic> body);
  Future<dynamic> sendMotivationDataUpdate(Map<String, dynamic> body);
  Future<dynamic> sendTeamRoleDataUpdate(Map<String, dynamic> body);
  Future<dynamic> sendSotQuestionListData(Map<String, dynamic> body);
  Future<dynamic> sendSotQuestionListCompletedData(Map<String, dynamic> body);
  Future<dynamic> sendDiagnosticQuestionListData(Map<String, dynamic> body);
  Future<dynamic> sendDiagnosticCompletedQuestionListData(Map<String, dynamic> body);
  Future<dynamic> sendTribeMeterQuestionListData(Map<String, dynamic> body);
  Future<dynamic> sendTribeMeterQuestionCompleteListData(Map<String, dynamic> body);
  Future<void> saveUserTeamRoleData(String userData);
  Future<void> saveUserMotivationData(String userData);
  Future<void> saveUserPersonalityTypeData(String userData);
  Future<void> saveSotQuestionListData(String userData);
  Future<void> saveDiagnosticQuestionListData(String userData);
  Future<void> saveTribeMeterQuestionListData(String userData);
  String getUserTeamRoleData();
  String getUserMotivationData();
  String getUserPersonalityTypeData();
  String getSotQuestionListData();
  String getDiagnosticListData();
  String getTribeMeterQuestionListData();
  Future<void> clearSavedUserTeamRoleData();
  Future<void> clearSavedUserMotivationData();
  Future<void> clearSavedPersonalityTypeData();
  Future<void> clearSotQuestionListData();
  Future<void> clearDiagnosticQuestionListData();
  Future<void> clearTribeMeterQuestionListData();
  Future<ApiResponse> viewActionList(Map<String, dynamic> body);
  Future<ApiResponse> updateActionItemStatus(Map<String, dynamic> body);
  Future<ApiResponse> deleteActionItemStatus(Map<String, dynamic> body);
  Future<ApiResponse> viewDepartmentUserList(Map<String, dynamic> body);
  Future<ApiResponse> viewUserByTypeList(Map<String, dynamic> body);
  Future<ApiResponse> viewThemeList(Map<String, dynamic> body);
  Future<ApiResponse> addActionData(Map<String, dynamic> body);
  Future<ApiResponse> updateActionData(Map<String, dynamic> body);
  Future<ApiResponse> viewCommentList(Map<String, dynamic> body);
  Future<ApiResponse> addCommentList(Map<String, dynamic> body);
  Future<ApiResponse> viewOrgDashboardReportWithFilter(Map<String, dynamic> body);
  Future<ApiResponse> viewActionTierList();
  Future<dynamic> viewDepartmentList();
  Future<dynamic> viewSotQuestionList();
  Future<dynamic> viewSotQuestionCompletedList();
  Future<dynamic> viewOfficeList(Map<String, dynamic> body);
  Future<dynamic> viewSupportHistoryList(Map<String, dynamic> body);
  Future<dynamic> addCustomerSupport(Map<String, dynamic> body);
  Future<dynamic> sendChatMessages(Map<String, dynamic> body);
  Future<dynamic> viewChatMessages(Map<String, dynamic> body);
  Future<dynamic> viewDiagnosticQuestionList();
  Future<dynamic> viewDiagnosticCompletedQuestionList();
  Future<dynamic> viewTribeMeterQuestionCompletedList();
  Future<dynamic> updatePushNotificationStatus(Map<String, dynamic> body);
}
