import '../../../../../data/model/api_response.dart';
import '../../../../../interface/repo_interface.dart';

abstract class ProfileRepositoryInterface implements RepositoryInterface {
  Future<ApiResponse> viewUserProfileData();
  Future<ApiResponse> viewQuestionsList();
  Future<ApiResponse> viewMotivationList();
  Future<ApiResponse> viewPersonalityTypeQuestionList();
  Future<ApiResponse> viewPersonalityTypeCompletedQuestionList();
  Future<ApiResponse> viewMotivationCompletedAnswerList();
  Future<ApiResponse> viewCompletedQuestionsList();
  Future<ApiResponse> getCOTMapperSummary();
  Future<ApiResponse> viewCOTindividualSummary();
  Future<ApiResponse> viewSOTmotivationUserList(Map<String, dynamic> loginBody);
  Future<ApiResponse> viewPersonalityTypeReport(Map<String, dynamic> loginBody);
  String getUserToken();
  Future<ApiResponse> updateProfile(Map<String, dynamic> body);
  Future<ApiResponse> viewCOTFunctionalLensDetail(Map<String, dynamic> body);
  Future<ApiResponse> sendTeamRoleData(Map<String, dynamic> body);
  Future<ApiResponse> sendPersonalityTypeData(Map<String, dynamic> body);
  Future<ApiResponse> sendPersonalityCompletedData(Map<String, dynamic> body);
  Future<ApiResponse> sendMotivationData(Map<String, dynamic> body);
  Future<ApiResponse> sendMotivationDataUpdate(Map<String, dynamic> body);
  Future<ApiResponse> sendTeamRoleDataUpdate(Map<String, dynamic> body);
  Future<void> saveUserTeamRoleData(String userData);
  Future<void> saveUserMotivationData(String userData);
  Future<void> saveUserPersonalityTypeData(String userData);
  String getUserTeamRoleData();
  String getUserMotivationData();
  String getUserPersonalityTypeData();
  Future<void> clearSavedUserTeamRoleData();
  Future<void> clearSavedUserMotivationData();
  Future<void> clearSavedPersonalityTypeData();
  Future<ApiResponse> viewActionList(Map<String, dynamic> body);
  Future<ApiResponse> updateActionItemStatus(Map<String, dynamic> body);
  Future<ApiResponse> deleteActionItemStatus(Map<String, dynamic> body);
  Future<ApiResponse> viewDepartmentUserList(Map<String, dynamic> body);
  Future<ApiResponse> viewUserByTypeList(Map<String, dynamic> body);
  Future<ApiResponse> viewThemeList(Map<String, dynamic> body);
  Future<ApiResponse> addActionData(Map<String, dynamic> body);
  Future<ApiResponse> viewActionTierList();
}
