import '../../../../../data/model/api_response.dart';
import '../../../../../interface/repo_interface.dart';

abstract class ProfileRepositoryInterface implements RepositoryInterface {
  Future<ApiResponse> viewUserProfileData();
  Future<ApiResponse> viewQuestionsList();
  Future<ApiResponse> viewMotivationList();
  Future<ApiResponse> viewPersonalityTypeQuestionList();
  Future<ApiResponse> viewPersonalityTypeCompletedQuestionList();
  Future<ApiResponse> viewMotivationCompletedAnswerList();
  Future<ApiResponse> viewCompletedQuestionsList();
  Future<ApiResponse> getCOTMapperSummary();
  Future<ApiResponse> viewCOTindividualSummary();
  Future<ApiResponse> viewSOTmotivationUserList(Map<String, dynamic> loginBody);
  Future<ApiResponse> viewPersonalityTypeReport(Map<String, dynamic> loginBody);
  Future<ApiResponse> viewTribeMeterQuestionList();
  String getUserToken();
  Future<ApiResponse> updateProfile(Map<String, dynamic> body);
  Future<ApiResponse> viewCOTFunctionalLensDetail(Map<String, dynamic> body);
  Future<ApiResponse> sendTeamRoleData(Map<String, dynamic> body);
  Future<ApiResponse> sendPersonalityTypeData(Map<String, dynamic> body);
  Future<ApiResponse> sendPersonalityCompletedData(Map<String, dynamic> body);
  Future<ApiResponse> sendMotivationData(Map<String, dynamic> body);
  Future<ApiResponse> sendMotivationDataUpdate(Map<String, dynamic> body);
  Future<ApiResponse> sendTeamRoleDataUpdate(Map<String, dynamic> body);
  Future<ApiResponse> sendSotQuestionListData(Map<String, dynamic> body);
  Future<ApiResponse> sendSotQuestionListCompletedData(Map<String, dynamic> body);
  Future<ApiResponse> sendDiagnosticQuestionListData(Map<String, dynamic> body);
  Future<ApiResponse> sendDiagnosticCompletedQuestionListData(Map<String, dynamic> body);
  Future<ApiResponse> sendTribeMeterQuestionListData(Map<String, dynamic> body);
  Future<ApiResponse> sendTribeMeterQuestionCompleteListData(Map<String, dynamic> body);
  Future<void> saveUserTeamRoleData(String userData);
  Future<void> saveUserMotivationData(String userData);
  Future<void> saveUserPersonalityTypeData(String userData);
  Future<void> saveSotQuestionListData(String userData);
  Future<void> saveDiagnosticQuestionListData(String userData);
  Future<void> saveTribeMeterQuestionListData(String userData);
  String getUserTeamRoleData();
  String getUserMotivationData();
  String getUserPersonalityTypeData();
  String getSotQuestionListData();
  String getDiagnosticListData();
  String getTribeMeterQuestionListData();
  Future<void> clearSavedUserTeamRoleData();
  Future<void> clearSavedUserMotivationData();
  Future<void> clearSavedPersonalityTypeData();
  Future<void> clearSotQuestionListData();
  Future<void> clearDiagnosticQuestionListData();
  Future<void> clearTribeMeterQuestionListData();
  Future<ApiResponse> viewActionList(Map<String, dynamic> body);
  Future<ApiResponse> updateActionItemStatus(Map<String, dynamic> body);
  Future<ApiResponse> deleteActionItemStatus(Map<String, dynamic> body);
  Future<ApiResponse> viewDepartmentUserList(Map<String, dynamic> body);
  Future<ApiResponse> viewUserByTypeList(Map<String, dynamic> body);
  Future<ApiResponse> viewThemeList(Map<String, dynamic> body);
  Future<ApiResponse> addActionData(Map<String, dynamic> body);
  Future<ApiResponse> updateActionData(Map<String, dynamic> body);
  Future<ApiResponse> viewCommentList(Map<String, dynamic> body);
  Future<ApiResponse> addCommentList(Map<String, dynamic> body);
  Future<ApiResponse> viewOrgDashboardReportWithFilter(Map<String, dynamic> body);
  Future<ApiResponse> viewActionTierList();
  Future<ApiResponse> viewOfficeList(Map<String, dynamic> body);
  Future<ApiResponse> viewSupportHistoryList(Map<String, dynamic> body);
  Future<ApiResponse> addCustomerSupport(Map<String, dynamic> body);
  Future<ApiResponse> viewChatMessages(Map<String, dynamic> body);
  Future<ApiResponse> sendChatMessages(Map<String, dynamic> body);
  Future<ApiResponse> viewDepartmentList();
  Future<ApiResponse> viewSotQuestionList();
  Future<ApiResponse> viewSotQuestionCompletedList();
  Future<ApiResponse> viewDiagnosticQuestionList();
  Future<ApiResponse> viewDiagnosticCompletedQuestionList();
  Future<ApiResponse> viewTribeMeterQuestionCompletedList();
  Future<ApiResponse> updatePushNotificationStatus(Map<String, dynamic> body);
}
